from .error import Error

def test():
    e = Error()
    e.error2()
